AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Configuration

Metadata: #파라미터들의 그룹들을 Label 작업
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - VpcCIDR
          - PubCIDR1
          - PubCIDR2
          - PriCIDRWEB1
          - PriCIDRWEB2
          - PriCIDRWAS1
          - PriCIDRWAS2
          - PriCIDRDB1
          - PriCIDRDB2


          
Parameters:   
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC ex(10.0.0.0/16)
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

  PubCIDR1:
    Description: Please enter the IP range (CIDR notation) ex(10.0.1.0/24)
    Type: String
    Default: 10.0.1.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  PubCIDR2:
    Description: Please enter the IP range (CIDR notation) ex(10.0.2.0/24)
    Type: String
    Default: 10.0.2.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

  PriCIDRWEB1:
    Description: Please enter the IP range (CIDR notation) ex(10.0.10.0/24)
    Type: String
    Default: 10.0.10.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  PriCIDRWEB2:
    Description: Please enter the IP range (CIDR notation) ex(10.0.20.0/24)
    Type: String
    Default: 10.0.20.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

  PriCIDRWAS1:
    Description: Please enter the IP range (CIDR notation) ex(10.0.30.0/24)
    Type: String
    Default: 10.0.30.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  PriCIDRWAS2:
    Description: Please enter the IP range (CIDR notation) ex(10.0.40.0/24)
    Type: String
    Default: 10.0.40.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

  PriCIDRDB1:
    Description: Please enter the IP range (CIDR notation) ex(10.0.50.0/24)
    Type: String
    Default: 10.0.50.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  PriCIDRDB2:
    Description: Please enter the IP range (CIDR notation) ex(10.0.60.0/24)
    Type: String
    Default: 10.0.60.0/24
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    
    
    
    
Resources:
  # Group1. Network Resource Define
  # 중첩 Stack VPC 
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://formation-lsh.s3.ap-northeast-2.amazonaws.com/cross_stack(Network).yml'
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PubCIDR1: !Ref PubCIDR1
        PubCIDR2: !Ref PubCIDR2
        PriCIDRWEB1: !Ref PriCIDRWEB1
        PriCIDRWEB2: !Ref PriCIDRWEB2
        PriCIDRWAS1: !Ref PriCIDRWAS1
        PriCIDRWAS2: !Ref PriCIDRWAS2
        PriCIDRDB1: !Ref PriCIDRDB1
        PriCIDRDB2: !Ref PriCIDRDB2
  SGstack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://formation-lsh.s3.ap-northeast-2.amazonaws.com/cross_stack(sg).yml'
      Parameters:
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID         
