AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Configuration

Metadata: #파라미터들의 그룹들을 Label 작업
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - KeyName
          - InstanceType

          
Parameters: 
  InstanceType:
    Type: String
    Default: t2.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select your Keypair

    
    
Resources:
  # Group1. Network Resource Define
  # 중첩 Stack VPC 
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://formation-lsh.s3.ap-northeast-2.amazonaws.com/cross_stack(Network).yml'
  SGStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://formation-lsh.s3.ap-northeast-2.amazonaws.com/cross_stack(sg).yml'
      Parameters:
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID         
  LBStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://formation-lsh.s3.ap-northeast-2.amazonaws.com/cross_stack(LB).yml'
      Parameters:
        VPCId:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID         
        InstanceType: !Ref InstanceType
        PublicSubnet1:
          Fn::GetAtt:              
          - VPCStack
          - Outputs.PublicSubnet1
        PublicSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2          
        EXLBsecurity: 
          Fn::GetAtt:        
          - SGStack
          - Outputs.EXLBsecurity
        PrivateSubnetWEB1:
          Fn::GetAtt:          
          - VPCStack
          - Outputs.PrivateSubnetWEB1
        PrivateSubnetWEB2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnetWEB2
        PrivateSubnetWAS1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnetWAS1
        PrivateSubnetWAS2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnetWAS2
        websecurity:
          Fn::GetAtt:
          - SGStack
          - Outputs.websecurity
        Key: !Ref KeyName
        sshsecurity:
          Fn::GetAtt:
          - SGStack
          - Outputs.sshsecurity



          
        

