AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Configuration

Metadata: #파라미터들의 그룹들을 Label 작업
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - KeyName
          - AMI

Mappings: # sample List ( 해당 리전에서 제공하는 AMI 및 리전의 각 AZ를 매핑)
  Regionmap:  
    ap-northeast-2:
      Linux2: ami-0f2c95e9fe3f8f80e
      window: ami-0685efd12a23690f5
          
Parameters: 
  AMI:
    Description: AMI of EC2
    Type: String
    Default: Linux2
    AllowedValues:
      - Linux2
      - window
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select your Keypair

    
    
Resources:
  # Group1. Network Resource Define
  # 중첩 Stack VPC 
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://formation-lsh.s3.ap-northeast-2.amazonaws.com/cross_stack(Network).yml'
  SGStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://formation-lsh.s3.ap-northeast-2.amazonaws.com/cross_stack(sg).yml'
      Parameters:
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID         
  LBStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://formation-lsh.s3.ap-northeast-2.amazonaws.com/cross_stack(LB).yml'
      Parameters:
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID         
        LBSubnets:
          Fn::GetAtt:              
          - VPCStack
          - Outputs.PublicSubnet1
        LBSubnets:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2          
        LBSG: 
          Fn::GetAtt:        
          - SGStack
          - Outputs.EXLBsecurity
        ASGSubnets:
          Fn::GetAtt:          
          - VPCStack
          - Outputs.PrivateSubnetWEB1
        ASGSubnets:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnetWEB2
        ASGsg:
          Fn::GetAtt:
          - SGStack
          - Outputs.websecurity
        Key: !Ref KeyName



          
        

