AWSTemplateFormatVersion: "2010-09-09"
Description: VPC-Ec2  Configuration Formation Template Next Template This Template is Loadbalancer and AutoScaling Testing


Metadata: #파라미터들의 그룹들을 Label 작업
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Loadbalancer Configuration"
        Parameters: 
          - ELBSubnets
          - VPC

      - 
        Label: 
          default: "Amazon EC2 Configuration"
        Parameters: 
          - ASGSubnets
          - ASGsg
          - Key



Mappings: # sample List ( 해당 리전에서 제공하는 AMI 및 리전의 각 AZ를 매핑)
  Regionmap:  
    ap-northeast-2:
      Linux2: ami-0f2c95e9fe3f8f80e
      window: ami-0685efd12a23690f5
      

Parameters:
  EnvironmentName: #변수값으로 저장하여 리소스들의 공통된 네임 지정
    Description: A common name for your resources
    Type: String
  AMI:
    Description: AMI of EC2
    Type: String
    Default: Linux2
    AllowedValues:
      - Linux2
      - window
  Key:
    Description: choice your key
    Type: AWS::EC2::KeyPair::KeyName
  VPC:
    Description: Select your VPC 
    Type: AWS::EC2::VPC::Id 
  ELBSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: select your subnets 
    
  ASGSubnets:
    Description: select your subnets 
    Type: List<AWS::EC2::Subnet::Id>
  ASGsg:
    Type: AWS::EC2::SecurityGroup::Id
    Description: select your sg (ec2 used)
  OperatorEMail: #구독 알림을 요청할 이메일 (ex. 관리자)
    Description: write your email
    Type: String
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)

Resources:

  #########################################################
  #                                                       #
  #                         ALB                           #
  #                                                       #    
  #########################################################
  Loadbalancersg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      GroupName: !Sub ${EnvironmentName}-LBsg
      VpcId:
        !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-LB
      Subnets: !Ref ELBSubnets
      SecurityGroups:
        - !Ref Loadbalancersg
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-LB

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-TG
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
  #########################################################
  #                                                       #
  #                    AutoScaling                        #
  #                                                       #    
  #########################################################
  LaunchConf:
    Type: AWS::AutoScaling::LaunchConfiguration
    Description: Ec2 launch configuration
    Properties:
      ImageId: !FindInMap [Regionmap, !Ref 'AWS::Region', Linux2]
      InstanceType: t2.micro
      LaunchConfigurationName: !Sub ${EnvironmentName}-LC
      KeyName: !Ref Key 
      InstanceMonitoring: true
      SecurityGroups: 
        - !Ref ASGsg
      UserData:
        !Base64 |
        #!/bin/bash -ex
        amazon-linux-extras install -y epel
        yum install -y mariadb* php httpd php-mysql git stress
        git clone https://github.com/sanghyupLEE9/FormationtoAWS.git
        cp /FormationtoAWS/index.php /var/www/html/index.php
        systemctl enable httpd mariadb
        systemctl start httpd mariadb


  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Description: Logical Ec2 group
    Properties:
      MaxSize: 4
      MinSize: 2
      AutoScalingGroupName: !Sub ${EnvironmentName}-ASG
      Cooldown: 30 
      DesiredCapacity: 2
      LaunchConfigurationName: !Ref LaunchConf
      VPCZoneIdentifier: !Ref ASGSubnets
      TargetGroupARNs: 
        - !Ref ALBTargetGroup
      HealthCheckGracePeriod: 300
      HealthCheckType: ELB
      NotificationConfigurations:
      - TopicARN: !Ref SNSTopic
        NotificationTypes:
          - autoscaling:EC2_INSTANCE_LAUNCH
          - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
          - autoscaling:EC2_INSTANCE_TERMINATE
          - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: web-asg
        

  EC2Scaleuppolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref ASG
      AdjustmentType: ChangeInCapacity
      PolicyType: StepScaling
      MetricAggregationType: Average
      EstimatedInstanceWarmup: 60
      StepAdjustments:
        - MetricIntervalLowerBound: 0   #40~ 60 일때 1개 증가
          MetricIntervalUpperBound: 20
          ScalingAdjustment: 1
        - MetricIntervalLowerBound: 20 # 60 ~ 일때 2개 증가
          ScalingAdjustment: 2
  
  EC2Scaledownpolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref ASG
      AdjustmentType: ChangeInCapacity
      PolicyType: StepScaling
      MetricAggregationType: Average
      EstimatedInstanceWarmup: 60
      StepAdjustments:
         # 20 미만구간으로 다운시 2개감소
        - MetricIntervalUpperBound: -10
          ScalingAdjustment: -2
         
        - MetricIntervalLowerBound: -10 # 30 ~ 20 구간시 1개감소
          MetricIntervalUpperBound:  0
          ScalingAdjustment: -1
  #########################################################
  #                                                       #
  #                         SNS                           #
  #                                                       #    
  #########################################################
  SNSTopic: #생성할 주제 및 구독
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${EnvironmentName}SNS_testing
      FifoTopic: false
      TopicName: !Sub ${EnvironmentName}Topic
      # KmsMasterKeyId: 
      Subscription: #구독 생성
      - Endpoint: !Ref OperatorEMail
        Protocol: email
  #########################################################
  #                                                       #
  #                         Alarm                         #
  #                                                       #    
  #########################################################
  CPUHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-up if CPU is greater than 40% for 10 minutes
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: '2' # 지정된 시간의 반복횟수
      AlarmActions:
        - !Ref SNSTopic
        - !Ref EC2Scaleuppolicy
      AlarmName: CPUHighScaling
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 300 # 검사 시간
      Statistic: Average
      Threshold: 40
      TreatMissingData: missing
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref ASG
  
  CPULow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-down if CPU is Less than 30% for 10 minutes
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 2
      Period: 300
      Threshold: 30
      Statistic: Average
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      AlarmName: CPULowScaling
      AlarmActions:
        - !Ref SNSTopic
        - !Ref EC2Scaledownpolicy
      TreatMissingData: missing
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref ASG


        

Outputs:
  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref ALB

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt ALB.DNSName



        



 