AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch-SNS-Resource Monitoring

Metadata: #파라미터들의 그룹들을 Label 작업
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "List Ec2"
        Parameters: 
          - EC2List
          
      - 
        Label: 
          default: "SNS-cloudwatch"
        Parameters: 
          - OperatorEMailww

          

          
Parameters:
  EnvironmentName: #변수값으로 저장하여 리소스들의 공통된 네임 지정
    Description: A common name for your resources
    Type: String 

  EC2List: # 사용중인 Ec2에 대한 리소스 목록 선택
    Description: Ec2 resource List
    Type: List<AWS::EC2::Instance::Id>
  OperatorEMail: #구독 알림을 요청할 이메일 (ex. 관리자)
    Description: write your email
    Type: String
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    


Resources:
  SNSTopic: #생성할 주제 및 구독
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${EnvironmentName}SNS_testing
      FifoTopic: false
      TopicName: !Sub ${EnvironmentName}Topic
      # KmsMasterKeyId: 
      Subscription: #구독 생성
      - Endpoint: !Ref OperatorEMail
        Protocol: email
  
  Ec2cpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '300'
      EvaluationPeriods: '3'
      Threshold: '70'
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: 
        - !Ref SNSTopic
      TreatMissingData: missing 
      Dimensions:
      - Name: InstanceId
        Value: !Select [0, !Ref EC2List]
      
  Ec2cpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '300'
      EvaluationPeriods: '3'
      Threshold: '70'
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: 
        - !Ref SNSTopic
      TreatMissingData: missing 
      Dimensions:
      - Name: InstanceId
        Value: !Select [1, !Ref EC2List]



Outputs:
  SNS:
    Description: Create your Noti SNS TOpic
    Value: !Ref SNSTopic
